window.__envs = {
NEXT_PUBLIC_COLOR_THEME_DEFAULT: "light",
NEXT_PUBLIC_HOMEPAGE_HERO_BANNER_CONFIG: "{'background':['#28426d'],'text_color':['#FFFFFF']}",
NEXT_PUBLIC_APP_INSTANCE: "exptest",
NEXT_PUBLIC_NETWORK_ICON_DARK: "https://media.dachain.tech/logo/logo-icon-dark.svg",
NEXT_PUBLIC_APP_PROTOCOL: "https",
NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: "18",
NEXT_PUBLIC_STATS_API_HOST: "https://exptest.dachain.tech",
NEXT_PUBLIC_GIT_COMMIT_SHA: "",
NEXT_PUBLIC_STATS_API_BASE_PATH: "/microstats",
NEXT_PUBLIC_NETWORK_TOKEN_STANDARD_NAME: "DRC",
NEXT_PUBLIC_NETWORK_LOGO_DARK: "https://media.dachain.tech/logo/logo-full-dark.svg",
NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: "wss",
NEXT_PUBLIC_NETWORK_CURRENCY_NAME: "DAC Coin Testnet",
NEXT_PUBLIC_HAS_USER_OPS: "false",
NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: "tDACC",
NEXT_PUBLIC_HOMEPAGE_CHARTS: "['daily_txs']",
NEXT_PUBLIC_API_HOST: "exptest.dachain.tech",
NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: "a98938759ab7581dfab5aadc73bcbbae",
NEXT_PUBLIC_RE_CAPTCHA_APP_SITE_KEY: "6LeKRcQsAAAAAN8b7cYbIvLEbOo-mgf9n-c1vpC7",
NEXT_PUBLIC_APP_HOST: "exptest.dachain.tech",
NEXT_PUBLIC_GOOGLE_ANALYTICS_PROPERTY_ID: "G-5FGBERQXNP",
NEXT_PUBLIC_OTHER_LINKS: "[]",
NEXT_PUBLIC_FOOTER_LINKS: "[{'title':'DAC Blockchain','links':[{'text':'DAC Website','url':'https://www.dachain.tech'},{'text':'Latest News','url':'https://www.dachain.tech/news'},{'text':'Get Started','url':'https://www.dachain.tech/get-started'},{'text':'Whitepaper','url':'https://whitepaper.dachain.tech'},{'text':'Contacts','url':'https://www.dachain.tech/contacts'}]},{'title':'Community','links':[{'text':'Telegram','url':'https://t.me/dac_chain'},{'text':'X (Twitter)','url':'https://x.com/dac_chain'},{'text':'Discord','url':'https://discord.gg/dacchain'},{'text':'LinkedIn','url':'https://www.linkedin.com/company/dac-labs/'},{'text':'GitHub','url':'https://github.com/dacblockchain'}]}]",
NEXT_PUBLIC_PROMOTE_BLOCKSCOUT_IN_TITLE: "false",
NEXT_PUBLIC_API_PORT: "443",
NEXT_PUBLIC_HOMEPAGE_STATS: "['total_blocks','average_block_time','total_txs','wallet_addresses','gas_tracker']",
NEXT_PUBLIC_GIT_TAG: "",
NEXT_PUBLIC_ICON_SPRITE_HASH: "9c9e59bd",
NEXT_PUBLIC_NETWORK_ICON: "https://media.dachain.tech/logo/logo-icon.svg",
NEXT_PUBLIC_NETWORK_ID: "21894",
NEXT_PUBLIC_NETWORK_LOGO: "https://media.dachain.tech/logo/logo-full.svg",
NEXT_PUBLIC_APP_ENV: "production",
NEXT_PUBLIC_NETWORK_NAME: "DAC Inception Testnet",
NEXT_PUBLIC_NETWORK_RPC_URL: "https://rpctest.dachain.tech",
NEXT_PUBLIC_IS_TESTNET: "true",
NEXT_PUBLIC_NETWORK_SHORT_NAME: "DAC",
}
